import type { RatePair } from './types'

/** All rate pair definitions — the math/linguistic skeletons for word problems */
export const RATE_PAIRS: RatePair[] = [
  // ── Existing (decomposed from original 6 frames) ──────────────

  {
    id: 'slices-dollars-cost',
    category: 'money',
    xNoun: { singular: 'slice', plural: 'slices' },
    yNoun: { singular: 'dollar', plural: 'dollars' },
    rateVerb: { base: 'cost', thirdPerson: 'costs', pastTense: 'cost', gerund: 'costing' },
    xUnit: 'slices',
    yUnit: '$',
    xUnitPosition: 'suffix',
    yUnitPosition: 'prefix',
    xRole: 'acquired',
  },
  {
    id: 'weeks-inches-grow',
    category: 'growth',
    xNoun: { singular: 'week', plural: 'weeks' },
    yNoun: { singular: 'inch', plural: 'inches' },
    rateVerb: { base: 'grow', thirdPerson: 'grows', pastTense: 'grew', gerund: 'growing' },
    xUnit: 'weeks',
    yUnit: 'inches',
    xUnitPosition: 'suffix',
    yUnitPosition: 'suffix',
    xRole: 'elapsed',
  },
  {
    id: 'hours-miles-travel',
    category: 'distance',
    xNoun: { singular: 'hour', plural: 'hours' },
    yNoun: { singular: 'mile', plural: 'miles' },
    rateVerb: { base: 'travel', thirdPerson: 'travels', pastTense: 'traveled', gerund: 'traveling' },
    xUnit: 'hours',
    yUnit: 'miles',
    xUnitPosition: 'suffix',
    yUnitPosition: 'suffix',
    xRole: 'elapsed',
  },
  {
    id: 'weeks-dollars-save',
    category: 'money',
    xNoun: { singular: 'week', plural: 'weeks' },
    yNoun: { singular: 'dollar', plural: 'dollars' },
    rateVerb: { base: 'save', thirdPerson: 'saves', pastTense: 'saved', gerund: 'saving' },
    xUnit: 'weeks',
    yUnit: '$',
    xUnitPosition: 'suffix',
    yUnitPosition: 'prefix',
    xRole: 'elapsed',
  },
  {
    id: 'batches-cups-need',
    category: 'cooking',
    xNoun: { singular: 'batch', plural: 'batches' },
    yNoun: { singular: 'cup', plural: 'cups' },
    rateVerb: { base: 'need', thirdPerson: 'needs', pastTense: 'needed', gerund: 'needing' },
    xUnit: 'batches',
    yUnit: 'cups',
    xUnitPosition: 'suffix',
    yUnitPosition: 'suffix',
    xRole: 'acquired',
  },
  {
    id: 'bracelets-beads-use',
    category: 'crafts',
    xNoun: { singular: 'bracelet', plural: 'bracelets' },
    yNoun: { singular: 'bead', plural: 'beads' },
    rateVerb: { base: 'use', thirdPerson: 'uses', pastTense: 'used', gerund: 'using' },
    xUnit: 'bracelets',
    yUnit: 'beads',
    xUnitPosition: 'suffix',
    yUnitPosition: 'suffix',
    xRole: 'acquired',
  },

  // ── New rate pairs ─────────────────────────────────────────────

  {
    id: 'tickets-dollars-cost',
    category: 'money',
    xNoun: { singular: 'ticket', plural: 'tickets' },
    yNoun: { singular: 'dollar', plural: 'dollars' },
    rateVerb: { base: 'cost', thirdPerson: 'costs', pastTense: 'cost', gerund: 'costing' },
    xUnit: 'tickets',
    yUnit: '$',
    xUnitPosition: 'suffix',
    yUnitPosition: 'prefix',
    xRole: 'acquired',
  },
  {
    id: 'laps-meters-run',
    category: 'sports',
    xNoun: { singular: 'lap', plural: 'laps' },
    yNoun: { singular: 'meter', plural: 'meters' },
    rateVerb: { base: 'run', thirdPerson: 'runs', pastTense: 'ran', gerund: 'running' },
    xUnit: 'laps',
    yUnit: 'meters',
    xUnitPosition: 'suffix',
    yUnitPosition: 'suffix',
    xRole: 'acquired',
  },
  {
    id: 'days-pages-read',
    category: 'growth',
    xNoun: { singular: 'day', plural: 'days' },
    yNoun: { singular: 'page', plural: 'pages' },
    rateVerb: { base: 'read', thirdPerson: 'reads', pastTense: 'read', gerund: 'reading' },
    xUnit: 'days',
    yUnit: 'pages',
    xUnitPosition: 'suffix',
    yUnitPosition: 'suffix',
    xRole: 'elapsed',
  },
  {
    id: 'games-points-score',
    category: 'sports',
    xNoun: { singular: 'game', plural: 'games' },
    yNoun: { singular: 'point', plural: 'points' },
    rateVerb: { base: 'score', thirdPerson: 'scores', pastTense: 'scored', gerund: 'scoring' },
    xUnit: 'games',
    yUnit: 'points',
    xUnitPosition: 'suffix',
    yUnitPosition: 'suffix',
    xRole: 'elapsed',
  },
  {
    id: 'stickers-dollars-cost',
    category: 'money',
    xNoun: { singular: 'sticker', plural: 'stickers' },
    yNoun: { singular: 'dollar', plural: 'dollars' },
    rateVerb: { base: 'cost', thirdPerson: 'costs', pastTense: 'cost', gerund: 'costing' },
    xUnit: 'stickers',
    yUnit: '$',
    xUnitPosition: 'suffix',
    yUnitPosition: 'prefix',
    xRole: 'acquired',
  },
  {
    id: 'days-centimeters-grow',
    category: 'growth',
    xNoun: { singular: 'day', plural: 'days' },
    yNoun: { singular: 'centimeter', plural: 'centimeters' },
    rateVerb: { base: 'grow', thirdPerson: 'grows', pastTense: 'grew', gerund: 'growing' },
    xUnit: 'days',
    yUnit: 'cm',
    xUnitPosition: 'suffix',
    yUnitPosition: 'suffix',
    xRole: 'elapsed',
  },
  {
    id: 'scoops-dollars-cost',
    category: 'money',
    xNoun: { singular: 'scoop', plural: 'scoops' },
    yNoun: { singular: 'dollar', plural: 'dollars' },
    rateVerb: { base: 'cost', thirdPerson: 'costs', pastTense: 'cost', gerund: 'costing' },
    xUnit: 'scoops',
    yUnit: '$',
    xUnitPosition: 'suffix',
    yUnitPosition: 'prefix',
    xRole: 'acquired',
  },
]

/** Registry: look up a rate pair by id */
export const RATE_PAIR_REGISTRY = new Map<string, RatePair>(
  RATE_PAIRS.map(p => [p.id, p])
)
