/**
 * LLM Prompt Generator for session celebration songs.
 *
 * Uses @soroban/llm-client to generate Suno-compatible lyrics, style tags,
 * and a title based on session performance data.
 */

import { z } from 'zod'
import { llm } from '@/lib/llm'
import type { SongPromptInput } from './extract-session-stats'

// ============================================================================
// Output Schema
// ============================================================================

export const songLLMOutputSchema = z.object({
  lyrics: z
    .string()
    .describe('Song lyrics with 2-3 short verses and a chorus. Max 3000 characters.'),
  style: z
    .string()
    .describe(
      'Suno style tags (comma-separated). Always include "children, upbeat, encouraging". Vary the genre.'
    ),
  title: z.string().describe('A short, fun song title (max 80 characters).'),
})

export type SongLLMOutput = z.infer<typeof songLLMOutputSchema>

// ============================================================================
// System Prompt
// ============================================================================

const SYSTEM_PROMPT = `You are a songwriter who writes short, fun, personalized celebration songs for kids who just finished math practice. Your songs are generated by Suno AI, so follow these constraints:

RULES:
- Write 2-3 short verses plus a chorus (repeat chorus once)
- Keep lyrics under 3000 characters total (Suno limit)
- Use the kid's name naturally in at least one verse
- Reference their specific achievements (accuracy, streaks, skills they practiced)
- If accuracy is high (>85%), celebrate their excellence
- If accuracy is moderate (60-85%), celebrate effort and progress
- If accuracy is low (<60%), emphasize effort, growth mindset, and trying hard
- Keep language age-appropriate, positive, and encouraging
- Never mention specific numbers that might make a kid feel bad
- Vary the musical style to keep things fresh — rotate through pop, reggae, funk, hip-hop, folk, rock, etc.
- Style tags MUST always include: "children, upbeat, encouraging"
- The title should be catchy and relate to the kid's session

FORMAT your lyrics with [Verse 1], [Chorus], [Verse 2], [Chorus] sections.`

// ============================================================================
// Prompt Builder
// ============================================================================

function buildUserPrompt(input: SongPromptInput): string {
  const { player, currentSession, history } = input

  const accuracyPercent = Math.round(currentSession.accuracy * 100)
  const parts = currentSession.partTypes.join(', ')

  let historyNote = ''
  if (history.recentSessionCount > 0) {
    const avgPct = Math.round(history.averageAccuracy * 100)
    historyNote = `\nRecent history: ${history.recentSessionCount} sessions this week, ${avgPct}% average accuracy, trend: ${history.trend}.`
  }

  return `Write a celebration song for ${player.name} ${player.emoji} who just finished math practice!

Session details:
- Completed ${currentSession.problemsDone} out of ${currentSession.problemsTotal} problems
- Accuracy: ${accuracyPercent}%
- Best correct streak: ${currentSession.bestCorrectStreak} in a row
- Practice types: ${parts}
- Session length: ${currentSession.durationMinutes} minutes
- Used help: ${currentSession.helpUsed ? 'yes' : 'no'}${historyNote}`
}

// ============================================================================
// Generator
// ============================================================================

/**
 * Generate song lyrics, style, and title using the LLM.
 */
export async function generateSongPrompt(input: SongPromptInput): Promise<SongLLMOutput> {
  const fullPrompt = `${SYSTEM_PROMPT}\n\n---\n\n${buildUserPrompt(input)}`

  const response = await llm.call({
    prompt: fullPrompt,
    schema: songLLMOutputSchema,
  })

  return response.data
}
